version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=solomonoff.projektstudencki.pl
      - SUBDOMAINS=
      - VALIDATION=http
    volumes:
      - ./config:/config
      - ./repo:/repo
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  solomonoff:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "80"
        #command: "mvn spring-boot:run"
    command: "java -jar ./target/Compiler-0.0.1-SNAPSHOT.jar"
